spring:
  datasource:
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
